artifacts_root: artifacts



data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/anishmaks/SHIP_Classification_using_Resnet/raw/main/Images.zip
  local_data_file: artifacts/data_ingestion/Images.zip
  unzip_dir: artifacts/data_ingestion/extracted_data
  class_dirs: 
    - artifacts/data_ingestion/extracted_data/Carrier
    - artifacts/data_ingestion/extracted_data/Cruise
    - artifacts/data_ingestion/extracted_data/Cargo
    - artifacts/data_ingestion/extracted_data/Military
    - artifacts/data_ingestion/extracted_data/Tanker

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pth
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.pth
  params_classes: 5
  freeze_all: True
  freeze_till: 2
  params_learning_rate: 0.001

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.pth 


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pth


CLASS_NAMES:
  - Military
  - Cargo
  - Cruise
  - Carrier
  - Tanker




